
DEBUG_ENABLE			= yes

AUDIO_ENABLE = yes

SERIAL_DRIVER = usart

DEBUG_MATRIX_SCAN_RATE_ENABLE = no
CONSOLE_ENABLE = yes

ENCODER_ENABLE = no

CORTEX_ENABLE_WFI_IDLE = no
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = WS2812
