
#TRI_LAYER_ENABLE = yes

BIN_FOLDER = /workspaces
cp: $(FIRMWARE_FORMAT)
	printf "Copying $(TARGET).$(FIRMWARE_FORMAT) to $(BIN_FOLDER)/$(TARGET).$(FIRMWARE_FORMAT)" | $(AWK_CMD)
	$(COPY) $(BUILD_DIR)/$(TARGET).$(FIRMWARE_FORMAT) $(BIN_FOLDER)/$(TARGET).$(FIRMWARE_FORMAT) && $(PRINT_OK)

